name: tauon
version: git
summary: Tauon Music Box
description: |
  A desktop music player for playback of local audio files. Designed to be simple and streamlined, putting the user in control of their music collection. Uses GStreamer or optionally BASS Audio Library for playback.

grade: stable
confinement: strict
base: core18

apps:
  tauon:
    command: tauon.py
    extensions:
      - gnome-3-28
    plugs:
      - x11
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - home
      - removable-media
      - gsettings

parts:
  python-deps:
    plugin: python
    source: .
    python-version: python3
    requirements:
      - requirements.txt
    stage-packages:
      - libsdl2-2.0-0
      - libsdl2-image-2.0-0
      - fonts-noto
      - python3-gi
      - python3-cairo
      - gir1.2-notify-0.7
      - python3-gi-cairo
      - libgstreamer1.0-0
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-libav
      - libgpm2
  tauon:
    plugin: dump
    source: .
    override-build: |
      snapcraftctl build
      chmod +x tauon.py
    