name: tauon
version: git
adopt-info: tauon

grade: stable
confinement: strict
base: core18

apps:
  tauon:
    command: tauon.py
    environment:
      PYSDL2_DLL_PATH: $PYSDL2_DLL_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET
    extensions:
      - gnome-3-28
    plugs:
      - x11
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - home
      - removable-media
      - gsettings

parts:
  python-deps:
    plugin: python
    source: .
    python-version: python3
    requirements:
      - requirements.txt
    stage-packages:
      - libsdl2-2.0-0
      - libsdl2-image-2.0-0
      - fonts-noto
      - python3-gi
      - python3-cairo
      - gir1.2-notify-0.7
      - python3-gi-cairo
      - libgstreamer1.0-0
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-libav
      - libgpm2
  tauon:
    plugin: dump
    source: .
    parse-info: [extra/com.github.taiko2k.tauonmb.appdata.xml]
    override-build: |
      snapcraftctl build
      chmod +x tauon.py
