name: tauon
version: git
adopt-info: tauon

grade: stable
confinement: strict
base: core18

architectures:
  - amd64

apps:
  tauon:
    command: tauon.py
    common-id: com.github.taiko2k.tauonmb.desktop
    environment:
      PYSDL2_DLL_PATH: $PYSDL2_DLL_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET
    extensions:
      - gnome-3-28
    plugs:
      - x11
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - home
      - network
      - removable-media
      - gsettings
      - opengl
      - audio-playback
      - pulseaudio
    slots:
    - mpris

parts:
  python-deps:
    plugin: python
    source: .
    python-version: python3
    requirements:
      - requirements.txt
    stage-packages:
      - libsdl2-2.0-0
      - libsdl2-image-2.0-0
      - fonts-noto
      - python3-gi
      - python3-cairo
      - python3-dbus
      - python-gst-1.0
      - python3-gi-cairo
      - gir1.2-notify-0.7
      - libgstreamer1.0-0
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-pulseaudio
      - gstreamer1.0-libav
      - libgpm2
      - libslang2
      - libpulse0
      - libglu1-mesa
      - libgl1
      - ffmpeg
      - picard
      - p7zip-full
      - unrar
      - flac
  tauon:
    plugin: dump
    source: .
    parse-info: [extra/com.github.taiko2k.tauonmb.appdata.xml]
    override-build: |
      snapcraftctl build
      chmod +x tauon.py
    override-prime: |
      snapcraftctl prime
      # temp fix for https://github.com/marcusva/py-sdl2/issues/148
      cd /usr/lib/$SNAPCRAFT_ARCH_TRIPLET
      ln -sf libSDL2-2.0.so.0 libSDL2-2.0.so
      ln -sf libSDL2_image-2.0.so.0 libSDL2_image-2.0.so

slots:
  dbus-tauon:
    interface: dbus
    name: org.mpris.MediaPlayer2.tauon
    bus: session
